// Code generated by "stringer -type=Route -linecomment"; DO NOT EDIT.

package config

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RouteUnknown-0]
	_ = x[RouteJs-1]
	_ = x[RouteCss-2]
	_ = x[RouteReload-3]
	_ = x[RouteLabelsForFile-4]
	_ = x[RouteHtmlForFile-5]
	_ = x[RouteRunBlock-6]
	_ = x[RouteSave-7]
	_ = x[RouteImage-8]
	_ = x[RouteQuit-9]
	_ = x[RouteDebug-10]
	_ = x[RouteWebSocket-11]
}

const _Route_name = "RouteUnknownjscssreloadlabelsForFilehtmlForFilerunCodeBlocksaveimagequitdebugdebug"

var _Route_index = [...]uint8{0, 12, 14, 17, 23, 36, 47, 59, 63, 68, 72, 77, 82}

func (i Route) String() string {
	if i < 0 || i >= Route(len(_Route_index)-1) {
		return "Route(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Route_name[_Route_index[i]:_Route_index[i+1]]
}
