// Code generated by "stringer -type=EnumOs -linecomment"; DO NOT EDIT.

package internal

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OsUnknown-0]
	_ = x[OsLinux-1]
	_ = x[OsDarwin-2]
	_ = x[OsWindows-3]
}

const _EnumOs_name = "unknownlinuxdarwinwindows"

var _EnumOs_index = [...]uint8{0, 7, 12, 18, 25}

func (i EnumOs) String() string {
	if i < 0 || i >= EnumOs(len(_EnumOs_index)-1) {
		return "EnumOs(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EnumOs_name[_EnumOs_index[i]:_EnumOs_index[i+1]]
}
